"""add must_change_password to users

Revision ID: 4f70b123c51b
Revises: e84ae2e065b2
Create Date: 2026-07-10 22:49:23.331797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f70b123c51b'
down_revision = 'e84ae2e065b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # server_default='1' added by hand (not autogenerated) so this
    # migration succeeds against a database that already has existing
    # user rows — a NOT NULL column added with no default would
    # otherwise fail on any pre-existing rows.
    op.add_column('users', sa.Column('must_change_password', sa.Boolean(), nullable=False, server_default='1'))

    # NOTE: autogenerate also proposed an op.alter_column(...) on
    # transactions.transaction_type to widen its Enum with the two new
    # TRANSFER_OUT/TRANSFER_IN values. That's intentionally omitted
    # here: SQLite has no real ALTER COLUMN TYPE support (it doesn't
    # enforce enum membership at the database level at all — the
    # column is just a VARCHAR under the hood), so running that
    # statement against SQLite either no-ops or requires Alembic's
    # batch mode to rebuild the whole table for no actual behavior
    # change. The new enum values already work without any migration
    # because SQLite never validated the old ones either. On a
    # database that DOES enforce native enums (e.g. Postgres), this
    # comment is your reminder to add the appropriate
    # `ALTER TYPE ... ADD VALUE` migration for that backend instead.


def downgrade() -> None:
    op.drop_column('users', 'must_change_password')
