"""add soft delete to warehouses and locations, add product image path

Revision ID: e84ae2e065b2
Revises: ae3350f0ac57
Create Date: 2026-07-10 08:28:07.472505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e84ae2e065b2'
down_revision = 'ae3350f0ac57'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default='1' added by hand (not autogenerated) so this
    # migration succeeds against a database that already has existing
    # warehouse/location rows — a NOT NULL column added with no default
    # would otherwise fail on any pre-existing rows.
    op.add_column('locations', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='1'))
    op.add_column('products', sa.Column('image_path', sa.String(length=255), nullable=True))
    op.add_column('warehouses', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('warehouses', 'is_active')
    op.drop_column('products', 'image_path')
    op.drop_column('locations', 'is_active')
    # ### end Alembic commands ###
